# Generated by Django 4.0.4 on 2022-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='data',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
